# Generated by Django 5.0.4 on 2024-05-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_type',
            field=models.CharField(choices=[('news', 'Новость'), ('article', 'Статья')], default='article', max_length=10),
        ),
    ]
